GITHUB_TOKEN = "~[GITHUB_PERSONAL_TOKEN_0]~"
SLACK_WEBHOOK = "~[SLACK_WEBHOOK_URL_0]~-pipeline-deploy-webhook"
SONARQUBE_TOKEN = "~[PY_HARDCODED_SECRET_1]~"
SNYK_TOKEN = "~[PY_HARDCODED_SECRET_0]~"

ENVIRONMENT = "production"
DEPLOY_REGION = "us-east-1"
